#pragma once

// place overrides here

#define RGBLIGHT_SLEEP
#define RGBLIGHT_SPLIT
#define RGBLIGHT_LAYERS
// #define RGBLIGHT_LAYER_BLINK

#define RGBLIGHT_EFFECT_BREATHING
// #define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
// #define RGBLIGHT_EFFECT_SNAKE
// #define RGBLIGHT_EFFECT_KNIGHT
// #define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
// #define RGBLIGHT_EFFECT_RGB_TEST
// #define RGBLIGHT_EFFECT_ALTERNATING
// #define RGBLIGHT_EFFECT_TWINKLE

#define TAPPING_TERM 200

#define LONGPRESS_DELAY 150
#define LAYER_TOGGLE_DELAY 300
#define LAYER_SKIP_DELAY 1000

#define HSV_MINE_QW  10, 255, 160
#define HSV_MINE_LW 143, 255, 180
#define HSV_MINE_RS   0, 255, 200 //HSV_RED
#define HSV_MINE_FN   5, 255, 200
#define HSV_MINE_AD  80, 255, 200

#define VIAL_KEYBOARD_UID {0xFA, 0x3A, 0xA0, 0x6F, 0x21, 0x69, 0x5C, 0x37}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

//#define DYNAMIC_KEYMAP_MACRO_COUNT 4
